from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Sites_window(object):
    def setupUi(self, Sites_window):
        Sites_window.setObjectName("Sites_window")
        Sites_window.resize(800, 600)
        Sites_window.setStyleSheet("background-color: rgb(43, 43, 43);")
        self.centralwidget = QtWidgets.QWidget(parent=Sites_window)
        self.centralwidget.setObjectName("centralwidget")
        self.Home_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Home_button.setGeometry(QtCore.QRect(20, 110, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        self.Home_button.setFont(font)
        self.Home_button.setStyleSheet("QPushButton\n"
"{\n"
"color: white;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/icons8-homee-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Home_button.setIcon(icon)
        self.Home_button.setIconSize(QtCore.QSize(40, 40))
        self.Home_button.setFlat(True)
        self.Home_button.setObjectName("Home_button")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(15, 190, 151, 60))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton\n"
"{\n"
"color: white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/icons8-sitee-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 201, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"color: white;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/icons8-keyy-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(50, 50))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(670, 130, 91, 61))
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/icons8-eyes-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(65, 65))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(500, 151, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-color: white;\n"
"border-radius: 10% 10%;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(400, 210, 351, 321))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"text-color: white;")
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.tableWidget.setRowCount(999)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        item.setFont(font)
        item.setBackground(QtGui.QColor(255, 255, 255))
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(16)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 2, item)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(265, 182, 61, 61))
        self.pushButton_4.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/df647a6ef0fe82e3eaf4a8fe5914fdc5.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.login_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_password.setGeometry(QtCore.QRect(210, 285, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        self.login_password.setFont(font)
        self.login_password.setStyleSheet("border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-color: white;\n"
"border-radius: 10% 10%;\n"
"text-align: center;\n"
"text-color: white;")
        self.login_password.setText("")
        self.login_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_password.setObjectName("login_password")
        self.line_password = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_password.setGeometry(QtCore.QRect(210, 365, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        self.line_password.setFont(font)
        self.line_password.setStyleSheet("border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-color: white;\n"
"border-radius: 10% 10%;\n"
"text-align: center;\n"
"text-color: white;")
        self.line_password.setText("")
        self.line_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.line_password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_password.setObjectName("line_password")
        self.line_password_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_password_2.setGeometry(QtCore.QRect(210, 444, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        self.line_password_2.setFont(font)
        self.line_password_2.setStyleSheet("border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-color: white;\n"
"border-radius: 10% 10%;\n"
"text-align: center;\n"
"text-color: white;")
        self.line_password_2.setText("")
        self.line_password_2.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_password_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.line_password_2.setObjectName("line_password_2")
        self.login_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_text.setGeometry(QtCore.QRect(260, 253, 75, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        self.login_text.setFont(font)
        self.login_text.setStyleSheet("color: white;")
        self.login_text.setObjectName("login_text")
        self.login_text_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_text_2.setGeometry(QtCore.QRect(250, 330, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        self.login_text_2.setFont(font)
        self.login_text_2.setStyleSheet("color: white;")
        self.login_text_2.setObjectName("login_text_2")
        self.login_text_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_text_3.setGeometry(QtCore.QRect(250, 411, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        self.login_text_3.setFont(font)
        self.login_text_3.setStyleSheet("color: white;")
        self.login_text_3.setObjectName("login_text_3")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(686, 50, 61, 61))
        self.pushButton_5.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/icons8-close-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon5)
        self.pushButton_5.setIconSize(QtCore.QSize(55, 55))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.login_password_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.login_password_2.setGeometry(QtCore.QRect(500, 67, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(10)
        self.login_password_2.setFont(font)
        self.login_password_2.setStyleSheet("border-style: solid;\n"
"color: rgb(255, 255, 255);\n"
"border-width: 1px;\n"
"border-color: white;\n"
"border-radius: 10% 10%;\n"
"text-align: center;\n"
"text-color: white;")
        self.login_password_2.setText("")
        self.login_password_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.login_password_2.setObjectName("login_password_2")
        self.login_text_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_text_4.setGeometry(QtCore.QRect(510, 120, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        self.login_text_4.setFont(font)
        self.login_text_4.setStyleSheet("color: white;")
        self.login_text_4.setObjectName("login_text_4")
        self.login_text_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_text_5.setGeometry(QtCore.QRect(550, 35, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft New Tai Lue")
        font.setPointSize(14)
        self.login_text_5.setFont(font)
        self.login_text_5.setStyleSheet("color: white;")
        self.login_text_5.setObjectName("login_text_5")
        Sites_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Sites_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        Sites_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Sites_window)
        self.statusbar.setObjectName("statusbar")
        Sites_window.setStatusBar(self.statusbar)

        self.retranslateUi(Sites_window)
        QtCore.QMetaObject.connectSlotsByName(Sites_window)

    def retranslateUi(self, Sites_window):
        _translate = QtCore.QCoreApplication.translate
        Sites_window.setWindowTitle(_translate("Sites_window", "PassGuard"))
        self.Home_button.setText(_translate("Sites_window", " Home"))
        self.pushButton_2.setText(_translate("Sites_window", " Sites"))
        self.pushButton.setText(_translate("Sites_window", "   PassGuard"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Sites_window", "Website"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Sites_window", "Username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Sites_window", "Password"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.login_text.setText(_translate("Sites_window", "Website"))
        self.login_text_2.setText(_translate("Sites_window", "Username"))
        self.login_text_3.setText(_translate("Sites_window", "Password"))
        self.login_text_4.setText(_translate("Sites_window", "Master Password"))
        self.login_text_5.setText(_translate("Sites_window", "ID line"))